# Perform continuous integration tests on updates and pull requests
name: Build test
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ci_cache
        key: ${{ runner.os }}-build-${{ hashFiles('scripts/ci-install.sh') }}

    - name: Prepare build
      run: ./scripts/ci-install.sh

    - name: Build
      run: make

    - name: Upload compiled klipper binary
      uses: actions/upload-artifact@v4
      with:
        name: klipper.bin
        path: out/klipper.bin
